### ISSUE TITLE
Project Planning todo list

### ISSUE THREAD

**Issue by alexandervice** [alexandervice/venture-vector#1]
- [x] determine the goals of the project
- [x] title of project
- [x] wireframe project
- [x] make MVP & bonus list
- [x] agree on MVP and bonus list
- [x] decide on stack
- [x] determine member roles

**Comment by n3ndor** [comment]
MVP looks totally great in my opinion.
We can stick on MERN, maybe we want to implement too much new stuff
To work only backend or frontend could be hard, better go with functionality and we do both front and backend
