### ISSUE TITLE
Bonus To-Do

### ISSUE THREAD

**Issue by alexandervice** [alexandervice/venture-vector#12]
**Styling**
- [x] Dark Mode

**Languages**
- [ ] Incorporate TypeScript
- [ ] incorporate GraphQL

**Additional API**
- [ ] Weather
- [ ] Time zone

**Trip Features**
- [ ] Public featured page
- [x] Filter only real locations
- [ ] Budget calculator

**Deploy**
- [ ] Dockerize server image in ECR
- [ ] Create ECS Cluster + Deploy to cluster with load balancing
- [ ] Host Client build on S3 bundle and link to CloudFront
